Chapter8 基本的なログイン機構
tsuji-kota/Rails5.1 pull request #5
Opened 2024-06-27 12:48 UTC by tsuji-kota

### 実施内容
- セッションの管理
- ログイン機能の作成とテスト
- ログアウト機能の作成とテスト

### コメント
8章終了しました！😀
確認お願いいたします🙏

### 備考
- 主な学び
  - session管理の書き方
  - findとfind_byの違い
  - ||を使った代入方法
  - fixtureの使い方と概要

2024-06-28 01:55 UTC, muttsu-623 requested changes
@tsuji-kota 
いくつかコメントしたー！
せっかくだったらこの修正をしてPushして、再度レビュー依頼してもらえるかな？

2024-06-28 01:55 UTC, muttsu-623 commented on app/helpers/sessions_helper.rb
> +      !current_user.nil?
これでもいいかも
```suggestion
      current_user.present?
```

2024-06-28 01:55 UTC, muttsu-623 commented on app/models/user.rb
> +    end
あんまり Model.class_method で書かないかも
こういう書き方の方が多いかな
```ruby
class << self
  def digest(string)
    ...
  end
end
```

2024-06-28 01:55 UTC, muttsu-623 commented on config/routes.rb
> +  delete '/logout',  to: 'sessions#destroy'
ここ、この機会にせっかくだからresourceを利用してみて〜！
https://railsguides.jp/v5.1/routing.html

2024-06-28 01:55 UTC, muttsu-623 commented on config/routes.rb
> +  delete '/logout',  to: 'sessions#destroy'
読みながら修正してみてもらえると 👍🏻

2024-06-28 01:55 UTC, muttsu-623 commented on app/helpers/sessions_helper.rb
> +    def log_in(user)
インデントは基本半角スペース2つに揃えたほうがいいかな 👀 
```suggestion
module SessionsHelper
  def log_in(user)
```

2024-06-28 01:55 UTC, muttsu-623 commented on app/helpers/sessions_helper.rb
> +    def log_in(user)
このファイルもそうだし、他のファイルもちょこちょこ4つがありそう

2024-06-28 06:20 UTC, tsuji-kota commented on app/helpers/sessions_helper.rb
> +    def log_in(user)
```
Rails.application.routes.draw do
  root   'static_pages#home'
  
  resources :static_pages do
    collection do
      get :help
      get :about
      get :contact
    end
  end

  resources :users do
    collection do
      get :signup
      post :signup
    end
  end

  resources :sessions do
    collection do
      get :login
      post :login
      delete :logout
    end
  end

end
```

こう言う感じで考えたのですが、これだと名前付きパスが使用できないみたいなのでテストでエラーがでてしまうみたいでした.......

2024-06-28 06:24 UTC, tsuji-kota commented on config/routes.rb
> +  delete '/logout',  to: 'sessions#destroy'
```
Rails.application.routes.draw do
  root   'static_pages#home'
  
  resources :static_pages do
    collection do
      get :help
      get :about
      get :contact
    end
  end

  resources :users do
    collection do
      get :signup
      post :signup
    end
  end

  resources :sessions do
    collection do
      get :login
      post :login
      delete :logout
    end
  end

end
```

こう言う感じで考えたのですが、これだと名前付きパスが使用できないみたいなのでテストでエラーがでてしまうみたいでした.......

2024-06-28 06:26 UTC, tsuji-kota commented on app/helpers/sessions_helper.rb
> +      !current_user.nil?
レビューありがとうございます🙏
修正しましたので、ご確認よろしくお願いいたします！

2024-06-28 06:26 UTC, tsuji-kota commented on app/models/user.rb
> +    end
複数定義する際に、提案してくださった書き方の方が便利だと学びました！

2024-06-28 06:30 UTC, tsuji-kota commented on app/helpers/sessions_helper.rb
> +    def log_in(user)
その他のファイルも訂正しました！

2024-07-02 00:26 UTC, muttsu-623 commented on config/routes.rb
> +  delete '/logout',  to: 'sessions#destroy'
@tsuji-kota 
ごめん！たしかにね！
完全に読み違って勘違いしてた 🙏🏻 
ここはこのままでぢあ丈夫です！

2024-07-02 00:26 UTC, muttsu-623 approved these changes
LGTM 💯

2024-07-11 02:13 UTC, merged